### ISSUE TITLE
Codeforces api url not working

### ISSUE THREAD

**Issue by ranamahmud** [sjsakib/cfviz#27]
Link to the codeforces  api website in the readme not working. 
Current Readme Link: [http://codeforces.com/api/help](http://codeforces.com/api/help)
Current working API  Link: [https://codeforces.com/apiHelp](https://codeforces.com/apiHelp)
I want to fix it.

**Comment by sjsakib** [comment]
Please go ahead and fix it, sorry for late response

**Comment by ranamahmud** [comment]
Ok. Thanks for your response.

**Comment by ranamahmud** [comment]
Ok. Thanks for your response.
