### ISSUE TITLE
Cannot read property 'Do' of undefined

### ISSUE THREAD

**Issue by EndlessCheng** [sjsakib/cfviz#31]
https://cfviz.netlify.app/compare.html

![image](https://user-images.githubusercontent.com/7086966/125552324-31c5e02a-0bb7-4a5a-b9cb-f4f3bf37d7de.png)

**Comment by Dip707** [comment]
@sjsakib please check this, might be a small bug, will help the cp community very much if fixed

**Comment by sjsakib** [comment]
Duplicate of #30
