### ISSUE TITLE
feature request: solved by rating

### ISSUE THREAD

**Issue by krofna** [sjsakib/cfviz#8]
Now that problems have rating tags, is it possible for you to add a bar chart showing how many problems of each rating level have been solved?

**Comment by sjsakib** [comment]
So far they haven't exposed it in the [API](https://codeforces.com/api/help/objects#Problem). If they do, I'll add that.

**Comment by krofna** [comment]
It's exposed in the API now.

**Comment by sjsakib** [comment]
@krofna done. Thanks! Sorry it took so long.
